eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true # For local development. Set to false if you want to use the hostname in a DNS-enabled environment
    hostname: ${HOSTNAME:localhost}

spring:
  application:
    name: ${APP_NAME:ms-auth-tfm}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fallbackDb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

server:
  port: ${PORT:8080}
  fullAddress: ${HOST:http://localhost}:${PORT:${server.port}}

logging:
  level:
    org:
      springframework:
        web: INFO
        context:
          annotation:
            ClassPathBeanDefinitionScanner: INFO

security:
  jwt:
    secret-key: ${JWT_SECRET:changeme}
    expiration-time: ${JWT_EXPIRATION:3600000}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}

simulator:
  allowed-email: ${ALLOWED_EMAIL}
  secret-header-name: ${SECRET_HEADER_NAME}
  secret-header-value: ${SECRET_HEADER_VALUE}