spring:
  application:
    name: ${APP_NAME:ms-auth-tfm}
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/fallbackDb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false  # Puedes desactivarlo en producción

logging:
  level:
    root: INFO
    org:
      springframework:
        web: WARN

security:
  jwt:
    secret-key: ${JWT_SECRET:changeme}
    expiration-time: ${JWT_EXPIRATION:3600000}

eureka:
  instance:
    preferIpAddress: false
    non-secure-port-enabled: true
    secure-port-enabled: false
    non-secure-port: ${server.port}
    secure-port: 443
